<a href="https://colab.research.google.com/github/jagtappranav2721-cpu/ML-Internship-FlyRank/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

# Notebook Setup

This notebook connects to the FlyRank internship warehouse using a Hugging Face access token stored securely in Google Colab Secrets.

In [8]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

if HF_TOKEN:
    print("✅ Hugging Face token loaded successfully!")
else:
    print("❌ Token not found.")

✅ Hugging Face token loaded successfully!

In [9]:
!pip install -q huggingface_hub datasets duckdb pyarrow pandas

In [10]:
from huggingface_hub import login
from google.colab import userdata

login(token=userdata.get("HF_TOKEN"))

## Warehouse Schema Inspection

The following cells inspect the available warehouse tables and their schema to identify the fields that will be used in this notebook.

In [11]:
from huggingface_hub import whoami

print(whoami())

{'type': 'user', 'id': '6a14035e6a3592a1779b49e3', 'name': 'LEOd2705', 'fullname': 'Pranav Anand Jagtap', 'isPro': False, 'avatarUrl': '/avatars/09f7e360bd46cdfdc880df4d594a2dac.svg', 'orgs': [], 'auth': {'type': 'access_token', 'accessToken': {'displayName': 'internship', 'role': 'fineGrained', 'createdAt': '2026-07-26T14:44:38.421Z', 'fineGrained': {'canReadGatedRepos': True, 'global': [], 'scoped': [{'entity': {'_id': '6a14035e6a3592a1779b49e3', 'type': 'user', 'name': 'LEOd2705'}, 'permissions': ['repo.content.read']}]}}}}

In [12]:
from datasets import load_dataset

dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    split="train[:5]"
)

print(dataset.column_names)

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [13]:
from datasets import load_dataset

dim_content = load_dataset(
    "FlyRank/internship-warehouse",
    "dim_content",
    split="train[:5]"
)

print(dim_content.column_names)

dim_content.parquet: reconstructing file:   0%|          |  0.00B / 19.6MB

dim_content.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/519606 [00:00<?, ? examples/s]

['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted']

In [14]:
import duckdb
from google.colab import userdata

con = duckdb.connect()

con.execute(f"""
CREATE SECRET (
    TYPE huggingface,
    TOKEN '{userdata.get("HF_TOKEN")}'
)
""")

rel = "hf://datasets/FlyRank/internship-warehouse"

In [15]:
con.sql(f"""
SELECT COUNT(*)
FROM read_parquet(
'{rel}/fact_content_daily_performance/month=2025-01/*.parquet'
)
""")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│         1297 │
└──────────────┘

In [16]:
con.sql(f"""
SELECT
    MIN(report_date) AS earliest_date,
    MAX(report_date) AS latest_date,
    COUNT(*) AS total_rows
FROM read_parquet(
'{rel}/fact_content_daily_performance/**/*.parquet'
)
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────────────┬─────────────┬────────────┐
│ earliest_date │ latest_date │ total_rows │
│     date      │    date     │   int64    │
├───────────────┼─────────────┼────────────┤
│ 2025-01-27    │ 2026-06-30  │   78835655 │
└───────────────┴─────────────┴────────────┘

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

## Unit of Analysis
One row represents one content page observed during a single calendar month. Each row contains the search and content performance metrics available for that page during that month.

## Tables
This analysis uses the FlyRank warehouse content performance tables. The exact fact and dimension tables will be identified after inspecting the warehouse schema and will be used to construct the feature frame for this lane.

## Time Window
This notebook uses the mid-panel month **2026-03** for analysis and feature construction. The final month is intentionally excluded because it should remain an unseen outcome period for evaluation.

## Prediction / Ranking Objective
The objective is to rank content pages according to their refresh priority using historical search and content performance signals that were available at the decision time.

## Deliberately Excluded Information
Future performance metrics, outcome-period information, and any label-derived fields are deliberately excluded from the feature set to prevent target leakage and ensure that only information available at the decision moment is used.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

Before building the feature frame, the fields that will be used in this lane are grouped into four categories. This classification ensures that only information available at the decision time is used for modelling, while identifier fields and filtering fields are kept separate from predictive features.

| Field | Category | Reason |
|--------|----------|--------|
| gsc_impressions | Feature | Historical search visibility available before the refresh decision. |
| gsc_clicks | Feature | Historical search engagement available before the refresh decision. |
| gsc_avg_position | Feature | Historical average search ranking available before the refresh decision. |
| ga4_sessions | Feature | Historical website sessions available before the refresh decision. |
| ga4_engaged_sessions | Feature | Historical user engagement signal available before the refresh decision. |
| sessions_organic | Feature | Historical organic traffic available before the refresh decision. |
| scroll_events | Feature | Historical user engagement behaviour available before the refresh decision. |
| word_count | Feature | Describes the size of the content before any refresh activity. |
| search_volume | Feature | Represents keyword demand known before the refresh decision. |
| competition_level | Feature | Indicates the SEO competition associated with the content. |
| content_type | Context | Describes the type of content being analysed. |
| main_intent | Context | Indicates the primary search intent of the content. |
| report_date | Context | Defines the observation date used for filtering the analysis period. |
| client_hash_id | Context | Identifies the client associated with the content. |
| content_hash_id | Context | Identifies the content page. |
| gsc_data_available | Context | Indicates whether Search Console metrics are available for the record. |
| ga4_data_available | Context | Indicates whether GA4 metrics are available for the record. |
| Refresh Priority (Proxy) | Label | The warehouse does not contain an explicit refresh label, so a proxy target will be created later for the modelling exercise. |
| keyword_hash_id | Excluded | Identifier only; it does not provide predictive information. |
| url_hash_id | Excluded | Identifier only; it does not provide predictive information. |
| is_published | Excluded | Used only to filter valid published content rather than as a predictive feature. |
| is_deleted | Excluded | Used only to remove deleted content from the analysis. |

### Design Decisions

- **Features** are historical search, traffic, engagement and content characteristics that are available before a refresh decision is made.
- **Context** fields describe the observation or identify the content but are not used directly as predictive inputs.
- **Label** is represented by a proxy because the warehouse contains raw operational data rather than an explicit refresh score.
- **Excluded** fields are identifiers or filtering fields that do not contribute predictive value and therefore are not included in the feature set.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

#### Query 1 – Verify the Grain

The data contract states that one row represents one content page for one client on one report date. The following query checks whether each `(report_date, client_hash_id, content_hash_id)` combination is unique. If no duplicate combinations are returned, the grain defined in the data contract is verified.

In [17]:
con.sql(f"""
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT (report_date, client_hash_id, content_hash_id)) AS unique_rows
FROM read_parquet(
'{rel}/fact_content_daily_performance/month=2026-03/*.parquet'
)
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌────────────┬─────────────┐
│ total_rows │ unique_rows │
│   int64    │    int64    │
├────────────┼─────────────┤
│    9841378 │     9841378 │
└────────────┴─────────────┘

### Query 2 – Verify the Analysis Slice

The data contract specifies March 2026 as the analysis period. The following query verifies the selected slice by reporting the total number of records together with the earliest and latest report dates available within that month.

In [18]:
con.sql(f"""
SELECT
    COUNT(*) AS row_count,
    MIN(report_date) AS earliest_date,
    MAX(report_date) AS latest_date
FROM read_parquet(
    '{rel}/fact_content_daily_performance/month=2026-03/*.parquet'
);
""")

┌───────────┬───────────────┬─────────────┐
│ row_count │ earliest_date │ latest_date │
│   int64   │     date      │    date     │
├───────────┼───────────────┼─────────────┤
│   9841378 │ 2026-03-01    │ 2026-03-31  │
└───────────┴───────────────┴─────────────┘

**Observation**

The selected analysis slice contains all daily performance records for March 2026. The earliest and latest report dates confirm that the selected month has been correctly loaded, making it an appropriate time window for feature engineering and model development.

### Query 3 – Verify Data Availability

The data contract assumes that only records with valid Google Search Console data are used for analysis. The following query filters the selected analysis month using `gsc_data_available IS TRUE` and reports the number of rows that satisfy this requirement.

In [19]:
con.sql(f"""
SELECT
    COUNT(*) AS available_rows
FROM read_parquet(
    '{rel}/fact_content_daily_performance/month=2026-03/*.parquet'
)
WHERE gsc_data_available IS TRUE;
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌────────────────┐
│ available_rows │
│     int64      │
├────────────────┤
│        3611061 │
└────────────────┘

**Observation**

The query reports the number of records in the selected analysis month for which Google Search Console data is available. These are the records that can be reliably used for feature engineering because the required search performance metrics are present.

## Feature Engineering

The objective of this section is to construct a small feature frame for the selected analysis month (March 2026). Rather than using every available column, only five meaningful features are selected that represent different aspects of content performance.

The selected features capture:

- Search visibility
- Website traffic
- User engagement
- Content characteristics
- SEO competition

Each feature is available before the content refresh decision is made, ensuring that no future information is used during feature engineering.

### Selected Feature Frame

The following five features were selected for the feature frame.

| Feature | Why it was selected | Available at the decision moment because... |
|----------|---------------------|---------------------------------------------|
| **gsc_impressions** | Measures search visibility of a page. | Historical Search Console impressions are already known before deciding to refresh the page. |
| **ga4_sessions** | Represents website traffic received by the page. | Historical Analytics sessions are available before the refresh decision. |
| **ga4_engaged_sessions** | Measures meaningful user interaction with the content. | User engagement has already occurred and is available before the decision. |
| **word_count** | Represents the depth and comprehensiveness of the content. | The content length is a current property of the page and is known beforehand. |
| **competition_level** | Indicates how competitive the topic is in search results. | Competition level is an existing SEO characteristic available before content optimisation. |

In [20]:
feature_frame = con.sql(f"""
SELECT
    f.report_date,
    f.client_hash_id,
    f.content_hash_id,

    -- Selected Features
    f.gsc_impressions,
    f.ga4_sessions,
    f.ga4_engaged_sessions,
    d.word_count,
    d.competition_level

FROM read_parquet(
    '{rel}/fact_content_daily_performance/month=2026-03/*.parquet'
) AS f

INNER JOIN read_parquet(
    '{rel}/dim_content.parquet'
) AS d

ON
    f.client_hash_id = d.client_hash_id
    AND
    f.content_hash_id = d.content_hash_id

WHERE
    f.gsc_data_available IS TRUE;
""").df()

feature_frame.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,report_date,client_hash_id,content_hash_id,gsc_impressions,ga4_sessions,ga4_engaged_sessions,word_count,competition_level
0,2026-03-01,client_62f4a7e64f5e0096,content_2e6360ad20fd7107,4,<NA>,<NA>,2855,LOW
1,2026-03-01,client_62f4a7e64f5e0096,content_ac8663da7484669a,8,<NA>,<NA>,3281,LOW
2,2026-03-01,client_62f4a7e64f5e0096,content_39d7361b4945d504,12,<NA>,<NA>,3579,LOW
3,2026-03-01,client_62f4a7e64f5e0096,content_d49a012dcb924e31,5,<NA>,<NA>,2993,LOW
4,2026-03-01,client_62f4a7e64f5e0096,content_614baf2af4330bd7,21,<NA>,<NA>,3500,LOW

In [21]:
feature_frame.isnull().sum()

report_date                   0
client_hash_id                0
content_hash_id               0
gsc_impressions               0
ga4_sessions            1528366
ga4_engaged_sessions    1528366
word_count              1205426
competition_level        129770
dtype: int64

### Missing Value Assessment

The selected features were inspected for missing values. Google Search Console impressions are complete for the filtered dataset, while some Google Analytics metrics and content metadata contain missing values. These missing values reflect differences in data availability across clients and content items rather than errors introduced during feature engineering.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

## Leakage Demonstration

The warehouse release does not include a training label such as `is_declining_label` from the starter dataset. To demonstrate feature leakage, a temporary synthetic label is created from the available data. This label is used only to illustrate how including target information as a feature can artificially inflate model performance. It is removed immediately after the experiment.

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Start from the feature frame
leakage_demo = feature_frame.dropna().copy()

# Synthetic label for demonstration only
leakage_demo["synthetic_label"] = (
    leakage_demo["gsc_impressions"] >
    leakage_demo["gsc_impressions"].median()
).astype(int)

In [23]:
X = leakage_demo[
    [
        "ga4_sessions",
        "ga4_engaged_sessions",
        "word_count",
        "competition_level",
    ]
]

# Encode competition level
X = X.copy()
X["competition_level"] = X["competition_level"].astype("category").cat.codes

y = leakage_demo["synthetic_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

honest_score = accuracy_score(y_test, model.predict(X_test))

print("Honest Accuracy:", round(honest_score, 4))

Honest Accuracy: 0.6834

In [24]:
X_leak = X.copy()

# BAD PRACTICE: adding the target itself as a feature
X_leak["synthetic_label"] = y

X_train, X_test, y_train, y_test = train_test_split(
    X_leak, y,
    test_size=0.2,
    random_state=42
)

leak_model = DecisionTreeClassifier(random_state=42)
leak_model.fit(X_train, y_train)

leak_score = accuracy_score(y_test, leak_model.predict(X_test))

print("Accuracy with leakage:", round(leak_score, 4))

Accuracy with leakage: 1.0

In [25]:
X_leak = X_leak.drop(columns=["synthetic_label"])

print("Leaked feature removed.")

Leaked feature removed.

### Leakage Observation

A synthetic demonstration label was created to illustrate feature leakage because the warehouse dataset does not include a training label such as `is_declining_label`.

Using only valid historical features, the Decision Tree model achieved an accuracy of **68.34%**. After intentionally adding the synthetic label as an input feature, the model achieved **100% accuracy**, demonstrating how leakage can produce unrealistically optimistic results.

The leaked feature was immediately removed after the experiment. The final feature frame therefore contains only historical information that would be available at the decision moment, making it suitable for honest model development.

## Conclusion

In this notebook, a data contract was established for the selected analysis lane, the warehouse data was validated using SQL verification queries, and a five-feature frame was constructed from historical warehouse data. Missing values were assessed to understand data quality, and a feature leakage experiment demonstrated how including target-derived information can artificially inflate model performance. After removing the leaked feature, the final feature frame retained only historical information available at the decision moment, making it a suitable foundation for future machine learning modelling.

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.